
### local - 
POST http://localhost:12345/activity/execute HTTP/1.1


### cria registro para outra aplicação que será acionada pelo JB
POST https://nodejs-express-mysql-mgalvao.herokuapp.com/customers HTTP/1.1
Content-Type: application/json

{
  "email": "email@example.com",
  "name": "Nome do Contato",
  "active": 1
}